DROP DATABASE IF EXISTS menu;
CREATE Database IF NOT EXISTS menu;

USE menu;
DROP TABLE IF EXISTS food;
CREATE TABLE IF NOT EXISTS food (
	food_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(127) NOT NULL UNIQUE,
    calories INT NOT NULL,
    description VARCHAR(255)
);


