USE menu;
INSERT INTO food (name, calories) 
VALUES 
	('Cheerios', 60), 
	('Cinnamon Toast Crunch', 121),
	('Fruit Loops', 105),
	('Frosted Flakes', 131),
	('Raisin Bran', 131),
	('Rice Chex', 72),
	('Oatmeal', 90),
	('Raisins', 60),
	('Cream of Wheat', 90),
	('Brown Sugar', 85),
	('Banana', 111),
	('Grapes', 75),
	('Seasonal Fresh Fruit', 85),
	('Sliced Peaches', 49),
	('Mandarin Oranges', 62),
	('Unsweetened Applesause', 91),
	('Mott Strawberry Applesause', 91),
	('Blueberry Yogurt', 160),
	('Strawberry Yogurt', 160),
	('Vanilla Yogurt', 160),
	('Greek Vanilla Yogurt', 110),
	('Yogurt Parfait', 60),
	('GoGurt', 70),
	('Cheese and Fruit Plate', 240),
	('Whole Milk', 150),
	('Chocolate Milk', 160),
	('2% Milk', 120),
	('Lactaid', 90),
	('Soy Milk', 130),
	('Apple Juice', 60),
	('Orange Juice', 60),
	('Grape Juice', 60),
	('Cranberry Juice', 100),
	('Fruit Punch', 60),
	('Tomato Juice', 30),
	('Prune Juice', 80),
	('Tea Regular', 0),
	('Green Tea', 0),
	('Decaf Tea', 0),
	('Lemon Tea', 0),
	('Unsweetened Ice Tea', 0),
	('Orange Spice Tea', 0),
	('Sugar sachet', 11),
	('Coffee Regular ', 0),
	('Decaf Coffee', 0),
	('Creamer', 16),
	('Bottled Water', 0),
	('Hot Chocolate', 90),
	('Hard Boiled Egg', 76),
	('Scrambled Eggs', 91),
	('Omelet Plain', 135),
	('Omelet Scrambled Eggs', 91),
	('Diced tomatoes', 5),
	('Fresh Green Peppers', 3),
	('Fresh Mushrooms', 5),
	('Diced Onion', 5),
	('Cheddar Cheese', 73),
	('Spinach', 8),
	('Diced Ham', 16),
	('Feta Cheese', 52),
	('English Muffin Toasted', 120),
	('Egg', 115),
	('Egg Beaters', 45),
	('Bacon', 35),
	('Canadian Bacon', 15),
	('Sausage', 75),
	('Swiss Cheese Slice', 85),
	('Cheddar Cheese Slice', 85),
	('American Cheese Slice', 60),
	('French Toast', 171),
	('Pancakes', 64),
	('Bacon Strips Two', 97),
	('Sausage Links Bob Evans Two', 146),
	('Diced Breakfast Potatoes', 95),
	('Sliced Chedar Cheese', 90),
	('Plain Bagel', 129),
	('Plain Bagel Toasted', 129),
	('Cream Cheese', 70),
	('Stawberry Cream Cheese', 70),
	('Onion and Chive Cream Cheese', 70),
	('White Toast', 50),
	('Wheat Toast', 70),
	('English Muffin', 120),
	('Blueberry Muffin', 190),
	('Cinnamon Sugar Donut', 280),
	('Cinnamon Roll', 305),
	('Syrup', 110),
	('Margerine', 25),
	('Peanut Butter', 126),
	('Grape Jelly', 35),
	('Strawberry Jam', 35),
	('Salt', 0),
	('Pepper', 0),
	('Mrs. Dash', 0),
	('Homey', 25),
	('Lemon', 4),
	('Ketchup', 19)
    
;
